language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t richardprasad/docker-travis -f Dockerfile.dev .

script:
    - docker run -e CI=true richardprasad/docker-react npm run test